import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://meta-testing-delta.vercel.app",
    type: "website",
    images: [
      {
        url: "https://meta-testing-delta.vercel.app/logo.webp",
        width: 800,
        height: 600,
        alt: "Your Image Description",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
